title: Thuong D. Hoang
description: I am a cosmologist and astrophysicist specializing in Cosmic Microwaves Background (CMB) and roles of magnetic fields in star formation. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman