title: Thuong Duc Hoang
description: I am a cosmologist and astrophysicist. My expertise are in Cosmic Microwaves Background (CMB) and roles of magnetic fields in star formation. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman