title: Thuong Duc Hoang
description: I am a cosmologist and astrophysicist. My expertise is in Cosmic Microwaves Background (CMB) and Magnetic fields and star formation. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman