title: Thuong D. Hoang
description: I am a cosmologist specializing in Cosmic Microwaves Background and roles of magnetic fields in star formation. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman